### ISSUE TITLE
Events not appearing on Matamo dashboard

### ISSUE THREAD

**Issue by hannahcx** [terveystalo/react-native-matomo-sdk#25]
There seem to be no failures on my end, in the native code or non native code, but "no data" is appearing in Matamo. I have installed your example project, and run on android - seems to be working but no events tracked, and have tried running on ios but get this error: Pods/OpenSSL-Universal/ios/lib/libcrypto.a(bio_lib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.

**Comment by aeirola** [comment]
Okay, interesting. You have probably ensured that the matomo configuration and trackerUrl is correct, and that there aren't any networking issues. Have you also checked if there are any errors returned in the promises, and wether any errors or warnings are visible in the react native or android native logs.

As for the iOS issue, it seems as if it is related to React Native depending on OpenSSL library which seems to be causing some issues. See https://github.com/facebook/react-native/issues/28824. I don't think there is much we can do about it in this library though. In case the example project doesn't run as it is, I can of course try to configure it to work.

**Comment by hannahcx** [comment]
Hi, I was able to get my code to work using a domain I set up, but it doesn't work with my companies on-premise account! No fault of the repo code by the looks of it, but I'm not sure what config they have wrong on their end. You can close this issue unless you have any ideas on what they have done wrong config wise?

**Comment by aeirola** [comment]
Okay, glad to hear that you got the library to work. Maybe the tracker domain name was only available through some internal networking DNS server, which the mobile application wasn't able to resolve for some reason or another.

Thanks for updating the status of your issue. I'll close the issue.
