### ISSUE TITLE
Unable to see location or time spent in app

### ISSUE THREAD

**Issue by hannahcx** [terveystalo/react-native-matomo-sdk#27]
Android is not logging time spent in app (showing as 1s in Matamo UI), iOS working correctly.

**Comment by aeirola** [comment]
Hmm, sounds strange. Could it have something to do with not tracking screen views? Does it always show 1s for all uses even though you would have multiple screen view tracks etc?

Sounds like an issue with https://github.com/matomo-org/matomo-sdk-android. Maybe open an issue there?

**Comment by hannahcx** [comment]
Yes, I thought so so I tagged screen views, and spent a few minutes going slowly through pages, but it didn't seem to work. I thought this was different than matomo-sdk-android, or are you using the same code?

**Comment by aeirola** [comment]
This library is just a JS wrapper for react native based on the matomo-sdk-android and matomo-sdk-ios libraries. It really doesn't do much else than pass the calls directly to the platform specific native SDK.

**Comment by hannahcx** [comment]
Oh right, of course I misread and thought you meant the other react native library. I have opened a issue, and hopefully they will get back to me.

**Comment by hannahcx** [comment]
This issue relates to: https://github.com/matomo-org/matomo/issues/15593
Basically, two sessions get created when the user goes into the app, because we are using webviews for those screens, and therefore the app session only registers as 1 second. If this gets fixed, then there will be no issues, but it's a Matamo bug.

**Comment by aeirola** [comment]
Aah, so you are tracking the user both with native and web based matomo sdks? Yeah, that sounds like it could cause some issues on the matomo side. Not really sure what we could do to support that in this library though. Would it help if we try to provide access to some matomo session variables which could be reused on the web side?

**Comment by aeirola** [comment]
We are unfortunately deprecating this library, and archiving the repository. Please migrate to https://github.com/BonifyByForteil/react-native-matomo. Sorry for the inconvenience.
