### ISSUE TITLE
Need setVisitorID

### ISSUE THREAD

**Issue by hannahcx** [terveystalo/react-native-matomo-sdk#29]
Hello I need to be able to setVisitorID (not setUserID) this is to join up our app with our webviews. It is not available in this SDK

**Comment by aeirola** [comment]
Hi, that sounds like a useful feature, and something that would definitely be valuable to add.

But before I encourage you to create a PR for the feature, I unfortunately need to inform you that this library is not going to be maintained anymore in the long term. The organisations has moved from matomo to piwik PRO, and thus our efforts now lie in https://github.com/terveystalo/react-native-piwik-pro-sdk.

I would suggest to move towards using https://github.com/BonifyByForteil/react-native-matomo instead, as it still seems to be maintained. But if you are already using our library, and really need the feature here, do still feel free to create a PR for the feature. I'll merge PRs and create releases for the library as long as it is still in some use within the organisation.

**Comment by aeirola** [comment]
We are unfortunately deprecating this library, and archiving the repository. Please migrate to https://github.com/BonifyByForteil/react-native-matomo. Sorry for the inconvenience.
