### ISSUE TITLE
Feature parity with `react-native-matomo`

### ISSUE THREAD

**Issue by aeirola** [terveystalo/react-native-matomo-sdk#8]
Currently, the older `react-native-matomo` library contains some functionality which is still missing from this library. In order to make this a viable option, it should at least include the same functionality. 

List of implemented and missing functionality:

- [x]  `trackEvent`
- [x]  `trackView`
- [x]  `setUserId`
- [x]  `setCustomDimension`
- [ ] `trackAppDownload`
- [ ] `trackGoal`
- [ ] `trackCampaign`
- [ ] `trackContentImpression`
- [ ] `trackContentInteraction`
- [ ] `trackSearch`

**Comment by oidoug** [comment]
trackScreen?

**Comment by aeirola** [comment]
Screen view tracking is implemented as `trackView` function. I chose to use `trackView` instead of `trackScreen` as the Matomo documentation uses the term "page view" for tracks. Of course "page" isn't a very clear term in the mobile context, so I decided to go with just view. The native iOS Matomo SDK also uses track view as the command.

I'll update this issue to also list already implemented functionality, so that this becomes more clear.

**Comment by oidoug** [comment]
Ok, thank you for the clarification!

**Comment by maxowy** [comment]
And updates? Would be good to have the possibility to set the user's id

**Comment by aeirola** [comment]
@maxowy Apologies for the slow progress on implementing features for the SDK. Our current project doesn't have use for the unimplemented features, and I would feel uncomfortable implementing features which I wouldn't be able to ensure to be working well.

Thus if anyone is in need for features in the SDK, I would encourage to make a PR to implement the feature.

**Comment by aeirola** [comment]
We are unfortunately deprecating this library, and archiving the repository. Please migrate to https://github.com/BonifyByForteil/react-native-matomo. Sorry for the inconvenience.
