### ISSUE TITLE
Relation to react-native-matomo

### ISSUE THREAD

**Issue by aeirola** [terveystalo/react-native-matomo-sdk#9]
There exists another library similar to this one at [react-native-matomo](https://github.com/BonifyByForteil/react-native-matomo), which offers roughly the same functionality. Unfortunately the maintenance of the old library seems to be a bit low on resources, so we decided to produce a separate library which we can maintain for our own uses. Hopefully, in the future, we would be able to combine the libraries and share the maintenance burden.

**Comment by feruzm** [comment]
Is there way to remove app package name from links, when I do trackview it is adding `http://package.bundle.identifier/` to view. How I can customize that?

**Comment by aeirola** [comment]
> Is there way to remove app package name from links, when I do trackview it is adding `http://package.bundle.identifier/` to view. How I can customize that?

This library doesn't currently support that. Looking at the underlying Android and iOS native SDKs it seems like it would be possible to build support for it. Feel free to create an issue or even a PR for that if you find it valuable.

**Comment by feruzm** [comment]
> > Is there way to remove app package name from links, when I do trackview it is adding `http://package.bundle.identifier/` to view. How I can customize that?
> 
> This library doesn't currently support that. Looking at the underlying Android and iOS native SDKs it seems like it would be possible to build support for it. Feel free to create an issue or even a PR for that if you find it valuable.

I attempted and added here PR #28

**Comment by aeirola** [comment]
We are unfortunately deprecating this library, and archiving the repository. This clears up the relation to react-native-matomo which now remains as the only react native library for matomo. Please migrate to https://github.com/BonifyByForteil/react-native-matomo. Sorry for the inconvenience.
